name: mddt
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.1.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - attrs=21.4.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2022.3.29
  - cffi=1.15.0
  - click=8.0.4
  - cryptography=3.4.8
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - dataclasses=0.8
  - frozenlist=1.2.0
  - gast=0.4.0
  - google-pasta=0.2.0
  - hdf5=1.10.6
  - idna=3.3
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - keras-preprocessing=1.1.2
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libprotobuf=3.19.1
  - libstdcxx-ng=9.3.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - ncurses=6.3
  - oauthlib=3.2.0
  - openssl=1.1.1n
  - opt_einsum=3.3.0
  - pip=21.2.4
  - pyasn1=0.4.8
  - pycparser=2.21
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-flatbuffers=2.0
  - readline=8.1.2
  - requests=2.27.1
  - six=1.16.0
  - sqlite=3.38.2
  - tensorflow-base=2.4.1
  - tk=8.6.11
  - typing_extensions
  - tzdata=2022a
  - urllib3=1.26.9
  - xz=5.2.5
  - yarl=1.6.3
  - zlib=1.2.12
  - pip:
    - absl-py==1.0.0
    - antlr4-python3-runtime==4.8
    - cachetools==5.0.0
    - certifi==2021.10.8
    - charset-normalizer==2.0.12
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - cython==0.29.28
    - dm-control==1.0.2
    - dm-env==1.5
    - dm-tree==0.1.7
    - docker-pycreds==0.4.0
    - fasteners==0.17.3
    - filelock==3.7.0
    - flatbuffers==1.12
    - fonttools==4.33.3
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - glfw==2.5.3
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - gym==0.21.0
    - gym-notices==0.0.6
    - h5py==3.1.0
    - huggingface-hub==0.6.0
    - hydra-core==1.1.2
    - imageio==2.18.0
    - keras==2.8.0
    - keras-nightly==2.5.0.dev2021032900
    - kiwisolver==1.4.2
    - labmaze==1.0.5
    - libclang==14.0.1
    - lxml==4.8.0
    - markdown==3.3.6
    - matplotlib==3.5.1
    - numpy
    - omegaconf==2.1.2
    - packaging==21.3
    - pandas==1.4.2
    - pathtools==0.1.2
    - pillow==9.1.0
    - promise==2.3
    - protobuf==3.20.1
    - psutil==5.9.0
    - pyasn1-modules==0.2.8
    - pybullet==3.2.4
    - pycocotools==2.0.4
    - pyopengl==3.1.6
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - regex==2022.4.24
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scipy==1.8.0
    - seaborn==0.11.2
    - sentry-sdk==1.5.12
    - setproctitle==1.2.3
    - setuptools==62.1.0
    - shortuuid==1.0.9
    - smmap==5.0.0
    - stable-baselines3==1.5.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - tokenizers==0.12.1
    - torch==1.11.0
    - tqdm==4.64.0
    - transformers==4.20.1
    - typing-extensions
    - wandb==0.12.16
    - werkzeug==2.1.2
    - wheel==0.37.1
    - wrapt==1.12.1
    - zipp==3.8.0
